linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gofmt
    - misspell

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
